# @name generate-ai-completion
POST http://localhost:3333/ai/generate
Content-Type: application/json

{
    "videoId": "videoId",
    "temperature": 0.5,
    "template": "template: '''{transcription}'''",
}